#!/bin/bash
set -eu

if [ $# -ne 1 ]; then
    echo "usage: $0 <PATH_TO_PYTHON3.10>"
    exit 1
fi

PYTHON=$1
DEST=venv

"$PYTHON" -m venv "$DEST"
source "$DEST/bin/activate"
pip install --upgrade pip
pip install -e ./app2app

echo "activate venv:"
echo "source $DEST/bin/activate"
